### ISSUE TITLE
Initial TODO list

### ISSUE THREAD

**Issue by justvanrossum** [justvanrossum/nabla#1]
- [x] Come up with a name for the typeface (not containing the word "color")
- [x] Change the name of the repo and source file accordingly, adapt `build.sh`
- [x] Define initial gradient palette: how many colors? Which colors play which role?
- [x] Add gradients to the "sides"; this needs a "side-gradient" glyph layer containing open paths with named nodes. Node names will be mapped to colors.
- [x] Add a gradient to the "front": will this be a fixed colorline for all glyphs, or will individual glyphs need customization? If a per-glyph thing is needed, we can use a verical line representing the color line, and put it in a "front-gradient" glyph layer.
- [x] Add highlights; this needs a "highlight" glyph layer containing open paths that represent the highlights.
- ~[ ] Write code for shape exceptions, such as the dot on the `i`.~
- [x] Add fontbakery step to workflow

**Comment by ArthurTypearture** [comment]
We have changed our "dot-on-the-i" approach: we feel the variable extrude depth clashes too much between the 100 (lowest) extrude depth, the "3D ball" and the other weights. We also value the extrusion depth over the option to make Nabla one static weight with the 3D dots. To replace the balls we have created extruded cylinders.

So the second to last checkbox can be removed/ticked.
