### ISSUE TITLE
Misc fontbakery fixes

### ISSUE THREAD

**Issue by justvanrossum** [justvanrossum/nabla#26]
- [x] Add named instances (see also #22) `com.google.fonts/check/varfont_has_instances`
- [x] avar #25 `com.google.fonts/check/mandatory_avar_table`
- [x] gasp #24 `com.google.fonts/check/gasp`
- [x] prep #24 `com.google.fonts/check/smart_dropout`
- [x] fvar `com.google.fonts/check/varfont/regular_wght_coord` et al.
- [x] file name (depends on axis tags) `com.google.fonts/check/canonical_filename`
- [x] STAT axis values `com.google.fonts/check/STAT/gf-axisregistry` et al.
